Fix styles
TNTU-RS-internship/scalhive-theme pull request #65
Opened 2024-07-17 17:36 UTC by boddolk

Closes #63 
Corrected cookies banner in phone and other versions.(File: concent.html)
Added margin between the line in the footer and the contact form.(File: contacts-with-google-form.html)
Made the size of the main banner the same on every page(Files: site-header/page-header.html)
Removed final masage before footer.(Files: single/index.html)

2024-07-17 17:55 UTC, ya6lis requested changes

2024-07-17 17:55 UTC, ya6lis commented on layouts/index.html
> -
Fix this space

![image](https://github.com/user-attachments/assets/7f9f2ecd-56c9-4072-8ae7-09d61238ee1b)

2024-07-17 17:56 UTC, ya6lis requested changes

2024-07-17 17:56 UTC, ya6lis commented on layouts/index.html
Fix this space

![image](https://github.com/user-attachments/assets/7f9f2ecd-56c9-4072-8ae7-09d61238ee1b)

2024-07-17 19:59 UTC, boddolk commented on layouts/index.html
Там якщо не помиляюсь, то лінія прив'язана до посту і відносно розширення встановлює відстань

2024-07-17 21:19 UTC, ya6lis commented on layouts/index.html
Then connect it to the button and not to the posts

2024-07-18 12:37 UTC, boddolk commented
> I don`t see any changes here
> 
> ![image](https://private-user-images.githubusercontent.com/100092934/349955065-89f8fc0b-c4a4-4977-ae0f-50551785cf01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDYzOTIsIm5iZiI6MTcyMTMwNjA5MiwicGF0aCI6Ii8xMDAwOTI5MzQvMzQ5OTU1MDY1LTg5ZjhmYzBiLWM0YTQtNDk3Ny1hZTBmLTUwNTUxNzg1Y2YwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQxMjM0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjI1ZmI4ZDUzMjhmMWZkNDZiYWMxN2MwMTMwYzc3MGYxYTE5YzYzMjdkMmE3YjJlMjA2YTI4NTZiYWEwNmM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hUGgtMxXYr-gEZd5ySTfyAuWUS_umv4ycRxiUNpgJ5w)

![image](https://github.com/user-attachments/assets/b13b5fe4-9f60-40e0-9b16-f28f12b41eb6)
![image](https://github.com/user-attachments/assets/c0e5690c-d934-4372-9bfe-5731a52d1a14)
тестував за різних розширень, кругом все коректно

2024-07-18 12:40 UTC, ya6lis commented
> > I don`t see any changes here
> > ![image](https://private-user-images.githubusercontent.com/100092934/349955065-89f8fc0b-c4a4-4977-ae0f-50551785cf01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDYzOTIsIm5iZiI6MTcyMTMwNjA5MiwicGF0aCI6Ii8xMDAwOTI5MzQvMzQ5OTU1MDY1LTg5ZjhmYzBiLWM0YTQtNDk3Ny1hZTBmLTUwNTUxNzg1Y2YwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQxMjM0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjI1ZmI4ZDUzMjhmMWZkNDZiYWMxN2MwMTMwYzc3MGYxYTE5YzYzMjdkMmE3YjJlMjA2YTI4NTZiYWEwNmM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hUGgtMxXYr-gEZd5ySTfyAuWUS_umv4ycRxiUNpgJ5w)
> 
> ![image](https://private-user-images.githubusercontent.com/168576160/349956369-b13b5fe4-9f60-40e0-9b16-f28f12b41eb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDY1NTksIm5iZiI6MTcyMTMwNjI1OSwicGF0aCI6Ii8xNjg1NzYxNjAvMzQ5OTU2MzY5LWIxM2I1ZmU0LTlmNjAtNDBlMC05YjE2LWYyOGYxMmI0MWViNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQxMjM3MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjkwM2MwMmY4M2Q0YTQzMWJhNzk0YjQ0YzIxNmE5MDE1MGVlODg2MjVmOGM0ODhkNjg4N2RhZGI0MWY4N2ZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H-VLh8XDgp-ud4-Dk0R3-F0eHTPid90QTNFfZTDBdHM) ![image](https://private-user-images.githubusercontent.com/168576160/349956462-c0e5690c-d934-4372-9bfe-5731a52d1a14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDY1NTksIm5iZiI6MTcyMTMwNjI1OSwicGF0aCI6Ii8xNjg1NzYxNjAvMzQ5OTU2NDYyLWMwZTU2OTBjLWQ5MzQtNDM3Mi05YmZlLTU3MzFhNTJkMWExNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQxMjM3MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2ZiOThiM2Y2MGI2OTU4MmE2YmI3MTg1MTRkZGYzZTc1MDhhYjdjZDZjYTgyNjdhYTEwOWY0MzlkM2VkOTc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w4Zg2gMZXpXLSDx8hbbToBdThsErVGZfK8dy8_Uk6XA) тестував за різних розширень, кругом все коректно

Sry, my bad, browser just don`t delete cache

2024-07-18 12:40 UTC, ya6lis approved these changes

2024-07-18 12:41 UTC, ya6lis commented
@boddolk You can merge it

2024-07-18 12:42 UTC, merged